=== Dexels/navajo/schemas/navascript.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.navajo.nl/schemas/xml.xsd"/>
    <!-- Top level navascript -->
    <xs:complexType name="TopLevel">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" ref="validations"/>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="message"/>
                <xs:element ref="property"/>
                <xs:element ref="include"/>
                <xs:element ref="param"/>
                <xs:element ref="methods"/>
                <xs:element ref="map"/>
                <xs:element ref="break"/>
                <xs:element ref="debug"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="author" type="xs:string"/>
        <xs:attribute name="description" type="xs:string"/>
        <xs:attribute name="repository" type="xs:string"/>
        <xs:attribute name="notes" type="xs:string"/>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
    <xs:element name="navascript" type="TopLevel"/>
    <xs:element name="tsl" type="TopLevel"/>
    <xs:element name="validations">
        <xs:complexType>
            <xs:choice>
                <xs:element maxOccurs="unbounded" ref="check"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="check">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="code" type="xs:integer" use="required"/>
                    <xs:attribute name="condition" type="xs:string" use="optional"/>
                    <xs:attribute ref="xml:space" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="methods">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="method"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="method">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element name="required">
                    <xs:complexType>
                        <xs:attribute name="message" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:attribute use="required" name="name" type="xs:string"/>
            <xs:attribute name="description" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="message">
        <xs:annotation>
            <xs:documentation>A message groups properties and other messages</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="message"/>
                <xs:element ref="property"/>
                <xs:element ref="param"/>
                <xs:element ref="map"/>
                <xs:element ref="break"/>
                <xs:element ref="debug"/>
            </xs:choice>
            <xs:attribute use="required" name="name" type="xs:string"/>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="mode" type="xs:string"/>
            <xs:attribute name="index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="map">
        <xs:annotation>
            <xs:documentation>A map maps Navajo and Java beans</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="message"/>
                <xs:element ref="property"/>
                <xs:element ref="param"/>
                <xs:element ref="map"/>
                <xs:element ref="field"/>
                <xs:element ref="break"/>
                <xs:element ref="debug"/>
                <xs:element maxOccurs="1" minOccurs="0" ref="request"/>
                <xs:element maxOccurs="1" minOccurs="0" ref="response"/>
                <xs:element maxOccurs="1" minOccurs="0" ref="running"/>
            </xs:choice>
            <xs:attribute name="object" type="xs:string"/>
            <xs:attribute name="condition" type="xs:string"/>
            <xs:attribute name="filter" type="xs:string"/>
            <xs:attribute name="ref" type="xs:string"/>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="field">
        <xs:annotation>
            <xs:documentation>A field is used a Java bean setter</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="1">
                <xs:element ref="expression"/>
            </xs:choice>
            <xs:attribute use="required" name="name" type="xs:string"/>
            <xs:attribute name="condition" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="property">
        <xs:annotation>
            <xs:documentation>A property is the basic data element</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="option"/>
                <xs:element ref="expression"/>
            </xs:choice>
            <xs:attribute use="required" name="name" type="xs:string"/>
            <xs:attribute name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:NMTOKEN">
                        <xs:enumeration value="boolean"/>
                        <xs:enumeration value="integer"/>
                        <xs:enumeration value="selection"/>
                        <xs:enumeration value="string"/>
                        <xs:enumeration value="date"/>
                        <xs:enumeration value="float"/>
                        <xs:enumeration value="binary"/>
                        <xs:enumeration value="money"/>
                        <xs:enumeration value="clocktime"/>
                        <xs:enumeration value="stopwatchtime"/>
                        <xs:enumeration value="percentage"/>
                        <xs:enumeration value="expression"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute use="required" name="direction">
                <xs:simpleType>
                    <xs:restriction base="xs:NMTOKEN">
                        <xs:enumeration value="in"/>
                        <xs:enumeration value="out"/>
                        <xs:enumeration value="inout"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="length" type="xs:integer"/>
            <xs:attribute name="cardinality" type="xs:string"/>
            <xs:attribute name="description" type="xs:string"/>
            <xs:attribute name="condition" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="param">
        <xs:annotation>
            <xs:documentation>A param is the basic variable element</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="1">
                <xs:element ref="option"/>
                <xs:element ref="expression"/>
            </xs:choice>
            <xs:attribute use="required" name="name" type="xs:string"/>
            <xs:attribute name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:NMTOKEN">
                        <xs:enumeration value="boolean"/>
                        <xs:enumeration value="integer"/>
                        <xs:enumeration value="selection"/>
                        <xs:enumeration value="string"/>
                        <xs:enumeration value="date"/>
                        <xs:enumeration value="float"/>
                        <xs:enumeration value="binary"/>
                        <xs:enumeration value="money"/>
                        <xs:enumeration value="clocktime"/>
                        <xs:enumeration value="stopwatchtime"/>
                        <xs:enumeration value="percentage"/>
                        <xs:enumeration value="expression"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute name="condition" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="option">
        <xs:annotation>
            <xs:documentation>Used in properties of type selection to define a list of (possibly selected) name/value pairs</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute use="required" name="name" type="xs:string"/>
            <xs:attribute use="required" name="value" type="xs:string"/>
            <xs:attribute use="required" name="selected">
                <xs:simpleType>
                    <xs:restriction base="xs:NMTOKEN">
                        <xs:enumeration value="1"/>
                        <xs:enumeration value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="expression">
        <xs:annotation>
            <xs:documentation/>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:element ref="value" maxOccurs="unbounded" minOccurs="0"/>
            </xs:choice>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute name="condition" type="xs:string"/>
            <xs:attribute ref="xml:space"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="value">
        <xs:annotation>
            <xs:documentation/>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:attribute name="condition" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="include">
        <xs:annotation>
            <xs:documentation/>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="script" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="comment">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="debug">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="break">
        <xs:complexType>
            <xs:attribute name="condition" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="request">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="include"/>
                <xs:element ref="param"/>
                <xs:element ref="field"/>
                <xs:element ref="property"/>
                <xs:element ref="message"/>
                <xs:element ref="map"/>
                <xs:element ref="comment"/>
                <xs:element ref="debug"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="response">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="include"/>
                <xs:element ref="param"/>
                <xs:element ref="field"/>
                <xs:element ref="property"/>
                <xs:element ref="message"/>
                <xs:element ref="map"/>
                <xs:element ref="comment"/>
                <xs:element ref="debug"/>
            </xs:choice>
            <xs:attribute name="while_running" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:NMTOKEN">
                        <xs:enumeration value="true"/>
                        <xs:enumeration value="false"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="running">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="include"/>
                <xs:element ref="param"/>
                <xs:element ref="field"/>
                <xs:element ref="property"/>
                <xs:element ref="message"/>
                <xs:element ref="map"/>
                <xs:element ref="comment"/>
                <xs:element ref="debug"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Dexels/navajo/scripts/ticket/ProcessQueryResources.xml
<?xml version="1.0" encoding="UTF-8"?>
<tsl author="Erik van der Weijden" id="ticket/ProcessQueryResources" notes="" repository="$Id$" xmlns="http://www.dexels.com/navascript"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dexels.com/navascript http://www.dexels.com/schema/navascript.xsd ">
    <param name="UpdateCount">
        <expression value="0" />
    </param>
    <map object="com.dexels.navajo.adapter.SQLMap">
        <field name="datasource">
            <expression value="'ticket'" />
        </field>
        <field name="query">
            <expression xml:space="preserve">
                SELECT R.resourceid, R.resourcename, R.typeofresource, R.resourcepath, R.resourceserver 
                FROM resources R, project P
                WHERE R.projectid = P.projectid
                AND P.projectid = ?
                AND R.typeofresource = ?     
            </expression>
        </field>
        <field name="parameter">
            <expression value="[/Resources/ProjectId]" />
        </field>
        <field name="parameter">
            <expression value="[/Resources/ResourceType]" />
        </field>
        <message name="ResourcesDetails">
            <map ref="resultSet">
                <property name="ResourceId">
                    <expression value="$columnValue('resourceid')" />
                </property>
                <property name="TypeOfResource">
                    <expression value="$columnValue('typeofresource')" />
                </property>
                <property name="ResourceName">
                    <expression value="$columnValue('resourcename')" />
                </property>
                <property name="ResourcePath">
                    <expression value="$columnValue('resourcepath')" />
                </property>
                <property name="ResourceServer">
                    <expression value="$columnValue('resourceserver')" />
                </property>
            </map>
        </message>
        
        
        <field name="query">
            <expression xml:space="preserve">
                INSERT INTO Changes (tickettreatid, typeofchange, resourceid) 
                VALUES      
            </expression>
        </field>
        <field name="parameter">
            <expression value="[/Resources/ProjectId]" />
        </field>
        <field name="parameter">
            <expression value="[/Resources/ResourceType]" />
        </field>
        <message name="ResourcesDetails">
            <map ref="resultSet">
                <property name="ResourceId">
                    <expression value="$columnValue('resourceid')" />
                </property>
                <property name="TypeOfResource">
                    <expression value="$columnValue('typeofresource')" />
                </property>
                <property name="ResourceName">
                    <expression value="$columnValue('resourcename')" />
                </property>
                <property name="ResourcePath">
                    <expression value="$columnValue('resourcepath')" />
                </property>
                <property name="ResourceServer">
                    <expression value="$columnValue('resourceserver')" />
                </property>
            </map>
        </message>
        
        
        
    </map>
</tsl>

=== Dexels/navajo/scripts/ticket/InitInsertOrganization.xml
<?xml version="1.0" encoding="UTF-8"?>
<tsl author="Erik" id="ticket/InitInsertOrganization" notes="" repository="$Id$" xmlns="http://www.dexels.com/navascript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dexels.com/navascript http://www.dexels.com/schema/navascript.xsd ">
	<methods>
		<method name="ticket/ProcessInsertOrganization">
			<required message="Organization" />
		</method>
	</methods>
	<message name="Organization">
		<property name="OrganizationName" type="string" direction="in" description="Naam van de Organizatie" />
		<map object="com.dexels.navajo.adapter.SQLMap">
			<field name="datasource">
				<expression value="'ticket'" />
			</field>			
		</map>
	</message>
</tsl>

=== Dexels/navajo/sample/Server/scripts/ticket/InitDeleteOrganization.xml
<?xml version="1.0" encoding="UTF-8"?>
<tsl author="Erik van der Weijden" id="ticket/InitDeleteOrganization" notes="" repository="$Id$" xmlns="http://www.dexels.com/navascript"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dexels.com/navascript http://www.dexels.com/schema/navascript.xsd ">
    <methods>
        <method name="ticket/ProcessDeleteOrganization" />
    </methods>
    <message name="Organization">

        <property name="OrganizationId" type="selection" direction="in">
            <option name="-" value="-1" selected="1" />
        </property>
        <map object="com.dexels.navajo.adapter.SQLMap">
            <field name="datasource">
                <expression value="'ticket'" />
            </field>
            <field name="query">
                <expression xml:space="preserve">
                  SELECT organizationid, organizationname FROM organization
                </expression>
            </field>
            <property name="OrganizationId" type="selection" direction="in">
                <map ref="resultSet">
                    <property name="name">
                        <expression value="$columnValue('organizationname')" />
                    </property>
                    <property name="value">
                        <expression value="$columnValue('organizationid')" />
                    </property>
                </map>
            </property>
        </map>
    </message>
</tsl>

=== Dexels/navajo/sample/Server/scripts/navajo/InitGetErrorLogOverview.xml
<?xml version="1.0" encoding="UTF-8"?>
<tsl author="Arjen Schoneveld" id="InitGetAccessLogOverview" xmlns="http://www.dexels.com/navascript"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dexels.com/navascript http://mail.dexels.com:8080/schema/navascript.xsd">
    <methods>
        <method name="navajo/ProcessGetAccessLog">
            <required message="AccessDetails"/>
        </method>
    </methods>
    <map object="com.dexels.navajo.adapter.SQLMap">
        <field name="datasource">
            <expression value="'navajostore'"/>
        </field>
        <field name="endIndex">
            <expression value="100"/>
        </field>
        <field name="query">
            <expression xml:space="preserve">
                SELECT 
                    CAST(navajoaccess.created AS DATE) AS datecreated,
                    navajoaccess.created,
                    navajoaccess.totaltime,
                    navajoaccess.parsetime,
                    navajoaccess.authorisationtime,
                    navajoaccess.requestsize,
                    navajoaccess.requestencoding,
                    navajoaccess.compressedrecv,
                    navajoaccess.compressedsnd,
                    navajoaccess.access_id,
                    navajoaccess.webservice,
                    navajoaccess.username,
                    navajoaccess.ip_address,
                    navajoaccess.hostname,
		    		navajolog.exception
                 FROM 
                   navajolog, navajoaccess
                 WHERE 
                   navajoaccess.access_id = navajolog.access_id
                 ORDER BY created DESC
             </expression>
        </field>
        <message name="AccessDetails">
            <property direction="in" name="AccessId" value="" description="AccessId" type="string" length="20"/>
        </message>
        <message name="LogOverview">
            <map ref="resultSet">
                <property name="CreatedDate" direction="out">
                    <expression value="$columnValue('datecreated')"/>
                </property>
                <property name="CreatedTime" direction="out">
                    <expression value="$columnValue('created')"/>
                </property>
                <property name="AccessId" direction="out">
                    <expression value="$columnValue('access_id')"/>
                </property>
                <property name="Webservice" direction="out">
                    <expression value="$columnValue('webservice')"/>
                </property>
                <property name="UserName" direction="out">
                    <expression value="$columnValue('username')"/>
                </property>
                <property name="IpAddress" direction="out">
                    <expression value="$columnValue('ip_address')"/>
                </property>
                <property name="Hostname" direction="out">
                    <expression value="$columnValue('hostname')"/>
                </property>
                <property name="TotalTime" direction="out">
                    <expression value="$columnValue('totaltime')"/>
                </property>
                <property name="ParseTime" direction="out">
                    <expression value="$columnValue('parsetime')"/>
                </property>
                <property name="AuthorisationTime" direction="out">
                    <expression value="$columnValue('authorisationtime')"/>
                </property>
                <property name="RequestSize" direction="out">
                    <expression value="$columnValue('requestsize')"/>
                </property>
                <property name="Encoding" direction="out">
                    <expression value="$columnValue('requestencoding')"/>
                </property>
                <property name="CompressedReceive" direction="out">
                    <expression value="$columnValue('compressedrecv') == 'TRUE'"/>
                </property>
                <property name="CompressedSend" direction="out">
                    <expression value="$columnValue('compressedsnd') == 'TRUE'"/>
                </property>
                <property name="HasException" direction="out">
                    <expression value="$columnValue('exception') != null AND ToString($columnValue('exception')) != 'No Exception'"/>
                </property>
            </map>
        </message>
    </map>
</tsl>

=== Dexels/navajo/sample_enterprise/scripts/navajo/description/ProcessDeleteDescription.xml
<?xml version="1.0" encoding="UTF-8"?>
<tsl xmlns="http://www.dexels.com/navascript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dexels.com/navascript http://mail.dexels.com:8080/schema/navascript.xsd">
    <map object="com.dexels.navajo.adapter.SQLMap">
        <field name="datasource">
            <expression value="'navajostore'"/>
        </field>
        <field name="query">
            <expression xml:space="preserve">
                 DELETE 
                 FROM 
                   propertydescription 
                 WHERE name = ? 
                 AND locale = ?
            </expression>
        </field>
        <field name="parameter">
            <expression value="[/Description/Name]"/>
        </field>
        <field name="parameter">
            <expression value="[/Description/Locale]"/>
        </field>
        <field name="doUpdate">
            <expression value="true"/>
            
        </field>
    </map>
</tsl>

=== Dexels/navajo/scripts/ticket/InitInsertPerson.xml
<?xml version="1.0" encoding="UTF-8"?>
<tsl author="Erik van der Weijden" id="ticket/InitInsertTicket" notes="" repository="$Id$" xmlns="http://www.dexels.com/navascript"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dexels.com/navascript http://www.dexels.com/schema/navascript.xsd ">
    <methods>
        <method name="ticket/ProcessInsertPerson">
            <required message="Person" />
        </method>
    </methods>
    <message name="Person">
        <property name="FirstName" type="string" direction="in" description="voornaam"/>
        <property name="Initials" type="string" direction="in" description="initialen"/>
        <property name="Infix" type="string" direction="in" description="infix"/>
        <property name="LastName" type="string" direction="in" description="achternaam"/>
        <property name="Tel" type="string" direction="in" description="telefoonnummer"/>
        <property name="Email" type="string" direction="in" description="email"/>
        <property name="SupportGroupId" type="selection" direction="in" description="supportgroepmedewerker">
            <option name="-" value="-1" selected="1" />
        </property>
        <map object="com.dexels.navajo.adapter.SQLMap">
            <field name="datasource">
                <expression value="'ticket'" />
            </field>
            <field name="query">
                <expression xml:space="preserve">
                SELECT supportgroupid, supportgroupname FROM supportgroup order by supportgroupname
            </expression>
            </field>
            <property name="SupportGroupId" type="selection" direction="in">
                <map ref="resultSet">
                    <property name="name">
                        <expression value="$columnValue('supportgroupname')" />
                    </property>
                    <property name="value">
                        <expression value="$columnValue('supportgroupid')" />
                    </property>
                </map>
            </property>
        </map>
        <property name="Organization" type="selection" direction="in" description="Werkzaam bij">
            <option name="-" value="-1" selected="1" />
        </property>
        
        <map object="com.dexels.navajo.adapter.SQLMap">
            <field name="datasource">
                <expression value="'ticket'" />
            </field>
            <field name="query">
                <expression xml:space="preserve">
                SELECT organizationid, organizationname FROM organization order by organizationname
            </expression>
            </field>
            <property name="Organization" type="selection" direction="in">
                <map ref="resultSet">
                    <property name="name">
                        <expression value="$columnValue('organizationname')" />
                    </property>
                    <property name="value">
                        <expression value="$columnValue('organizationid')" />
                    </property>
                </map>
            </property>
        </map>
        <property name="OrganizationRole" type="string" direction="in" description="Rol in de organisatie"/>
    </message>
</tsl>

=== Dexels/navajo/scripts/ticket/ProcessCheckAttachment.xml
<?xml version="1.0" encoding="UTF-8"?>
<tsl author="Erik van der Weijden" id="ticket/ProcessCheckattachment" notes="Check duplicate attachments" repository="$Id$" xmlns="http://www.dexels.com/navascript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dexels.com/navascript http://www.dexels.com/schema/navascript.xsd">
    <map object="com.dexels.navajo.adapter.SQLMap">
        <field name="datasource">
            <expression value="'sportlinkkernel'" />
        </field>
        <field name="query">
            <expression xml:space="preserve">
                SELECT COUNT(*) AS cnt
                FROM   attachment
                WHERE  LOWER(name) = ?
            </expression>
        </field>
        <field name="parameter">
            <expression value="ToLower([/Ticket/FileName])" />
        </field>
        <message name="Result">
            <property name="PossibleDuplicate" direction="out" description="Mogelijk dubbel bestand?">
                <expression value="$columnValue('cnt') &gt; 0" />
            </property>
        </message>
    </map>
</tsl>
